services:
  - type: web
    name: saturday-chatbot
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
      mkdir -p BACKEND/build
      cp -r build/* BACKEND/build/
    startCommand: gunicorn BACKEND.backend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    disk:
      name: data
      mountPath: /opt/render/project/src/BACKEND
      sizeGB: 1
